name: building bear web application
on:
  push:

jobs:

  build-dot-net:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3
      
      - name: deploy railway
        uses: railway up
