name: building bear web application
on:
  push:

jobs:

  build-dot-net:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3
      
      - name: deploy railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ 8bf6c8b0-f0a8-4618-b8ff-de6aa4c36876 }}
          service: "succinct-play"
