name: building bear web application
on:
  push:
    branches:
      - 'release/v1.0'

jobs:

  build-bears:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3
      
      - name: deploy railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "succinct-play"
      
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "DipSA 56 CI/CD Submission",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name:* ${{ secrets.NAME }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Email:* ${{ secrets.EMAIL }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Matriculation:* ${{ secrets.MATRICULATION }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:* ${{ secrets.REPOSITORY }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ secrets.RAILWAY_URL }}"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "${{ secrets.RAILWAY_URL }}",
                      "action_id": "button-action"
                    }
                  }
                ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

            